# Generated by Django 5.2.8 on 2025-11-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=128)),
                ('lastname', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=256)),
                ('jobtitle', models.CharField(max_length=128)),
                ('schoolname', models.CharField(max_length=128)),
                ('degree', models.CharField(max_length=64)),
                ('starttime', models.CharField(max_length=64)),
                ('endtime', models.CharField(max_length=64)),
                ('result_type', models.CharField(choices=[('C', 'cgpa'), ('G', 'gpa')], default='C', max_length=32)),
                ('score', models.IntegerField()),
                ('company', models.CharField(max_length=128)),
                ('role', models.CharField(max_length=128)),
                ('job_starttime', models.CharField(max_length=64)),
                ('job_endtime', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('skills', models.TextField()),
                ('project_name', models.CharField(max_length=128)),
                ('project_link', models.CharField(max_length=128)),
                ('project_starttime', models.CharField(max_length=64)),
                ('project_endtime', models.CharField(max_length=64)),
                ('project_description', models.TextField()),
                ('achievement_name', models.CharField(max_length=128)),
                ('achievement_time', models.CharField(max_length=64)),
            ],
        ),
    ]
