# Generated by Django 5.2.8 on 2025-11-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvform',
            name='platform_name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='cvform',
            name='profile_link',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
