# Generated by Django 5.2.8 on 2025-11-15 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cvform_platform_name_cvform_profile_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cvform',
            name='achievement_name',
        ),
        migrations.RemoveField(
            model_name='cvform',
            name='achievement_time',
        ),
        migrations.RemoveField(
            model_name='cvform',
            name='company',
        ),
        migrations.RemoveField(
            model_name='cvform',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='cvform',
            name='description',
        ),
        migrations.RemoveField(
            model_name='cvform',
            name='endtime',
        ),
        migrations.RemoveField(
            model_name='cvform',
            name='job_endtime',
        ),
        migrations.RemoveField(
            model_name='cvform',
            name='job_starttime',
        ),
        migrations.RemoveField(
            model_name='cvform',
            name='platform_name',
        ),
        migrations.RemoveField(
            model_name='cvform',
            name='profile_link',
        ),
        migrations.RemoveField(
            model_name='cvform',
            name='project_description',
        ),
        migrations.RemoveField(
            model_name='cvform',
            name='project_endtime',
        ),
        migrations.RemoveField(
            model_name='cvform',
            name='project_link',
        ),
        migrations.RemoveField(
            model_name='cvform',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='cvform',
            name='project_starttime',
        ),
        migrations.RemoveField(
            model_name='cvform',
            name='result_type',
        ),
        migrations.RemoveField(
            model_name='cvform',
            name='role',
        ),
        migrations.RemoveField(
            model_name='cvform',
            name='schoolname',
        ),
        migrations.RemoveField(
            model_name='cvform',
            name='score',
        ),
        migrations.RemoveField(
            model_name='cvform',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='cvform',
            name='starttime',
        ),
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_name', models.CharField(blank=True, max_length=128, null=True)),
                ('achievement_time', models.CharField(blank=True, max_length=64, null=True)),
                ('cvform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='api.cvform')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(blank=True, max_length=128, null=True)),
                ('profile_link', models.CharField(blank=True, max_length=128, null=True)),
                ('cvform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='api.cvform')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolname', models.CharField(blank=True, max_length=128, null=True)),
                ('degree', models.CharField(blank=True, max_length=64, null=True)),
                ('starttime', models.CharField(blank=True, max_length=64, null=True)),
                ('endtime', models.CharField(blank=True, max_length=64, null=True)),
                ('result_type', models.CharField(blank=True, choices=[('C', 'cgpa'), ('G', 'gpa')], default='C', max_length=32, null=True)),
                ('score', models.IntegerField()),
                ('cvform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='api.cvform')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=128)),
                ('role', models.CharField(max_length=128)),
                ('job_starttime', models.CharField(max_length=64)),
                ('job_endtime', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('cvform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='api.cvform')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, max_length=128, null=True)),
                ('project_link', models.CharField(blank=True, max_length=128, null=True)),
                ('project_starttime', models.CharField(blank=True, max_length=64, null=True)),
                ('project_endtime', models.CharField(blank=True, max_length=64, null=True)),
                ('project_description', models.TextField(blank=True, null=True)),
                ('cvform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api.cvform')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.TextField(blank=True, null=True)),
                ('cvform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='api.cvform')),
            ],
        ),
    ]
