# Generated by Django 5.2.8 on 2025-11-17 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_cvform_achievement_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='cvform',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='cvform',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='cvform',
        ),
        migrations.RemoveField(
            model_name='project',
            name='cvform',
        ),
        migrations.RemoveField(
            model_name='education',
            name='cvform',
        ),
        migrations.CreateModel(
            name='RequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('htmldata', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Achievements',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='CVform',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
    ]
